const express = require("express");
const router = express.Router();
const qrcode = require("qrcode");
const {
  CognitoIdentityProviderClient,
  AssociateSoftwareTokenCommand,
  VerifySoftwareTokenCommand,
  RespondToAuthChallengeCommand,
  AdminListGroupsForUserCommand,
} = require("@aws-sdk/client-cognito-identity-provider");
const { getClientId } = require("../utility/secretHandler");

const client = new CognitoIdentityProviderClient({ region: "ap-southeast-2" });

// MFA Setup: /mfa/setup
router.post("/setup", async (req, res) => {
  const { session } = req.body; // Use session from the challenge response
  //console.log("Initiating MFA setup with session: ", session);

  try {
    const command = new AssociateSoftwareTokenCommand({
      Session: session, // Use session here, not accessToken
    });

    const response = await client.send(command);
    const secretCode = response.SecretCode;
    //console.log("beep boop");
    //console.log(response);
    //console.log("boop beep");
    const issuer = "Spaghetti Sim"; // Replace with your app's name
    const otpauthURI = `otpauth://totp/${issuer}?secret=${secretCode}&issuer=${issuer}&digits=6&period=30`;

    const qrCodeImageUrl = await qrcode.toDataURL(otpauthURI);

    // Send the secret code (to be scanned by the user into their authenticator app)
    res.status(200).json({
      qrCodeImageUrl,
      secretCode, // This is the code the user will scan
      session: response.Session, // Keep the session for next steps
    });
  } catch (err) {
    console.error("Error initiating MFA setup:", err);
    res.status(500).json({ message: "Error initiating MFA setup", error: err });
  }
});

router.post("/verify", async (req, res) => {
  const { session, mfaCode } = req.body; // Use session and MFA code

  //console.log("Verifying MFA setup with code: ", mfaCode);
  //console.log("Using session: ", session);
  //console.log("Request body: ", req.body);

  try {
    const command = new VerifySoftwareTokenCommand({
      Session: session, // Use session here, not accessToken
      UserCode: mfaCode, // The MFA code generated by the user's authenticator app
    });

    const response = await client.send(command);
    //console.log("MFA verification response: ", response);

    // Check if the verification was successful
    if (response.Status === "SUCCESS") {
      res.status(200).json({
        message: "MFA setup successful",
        session: response.Session, // Return the session for the next step
      });
    } else {
      res.status(400).json({ message: "Failed to verify MFA code" });
    }
  } catch (err) {
    console.error("Error verifying MFA setup:", err);
    res.status(500).json({ message: "Error verifying MFA setup", error: err });
  }
});

router.post("/authenticate", async (req, res) => {
  const { session, mfaCode, email } = req.body; // Extract session, MFA code, and email

  //console.log("Authenticating user with MFA code: ", mfaCode);
  //console.log("Using session: ", session);
  //console.log("Request body: ", req.body);

  try {
    clientID = await getClientId();
    // Respond to the MFA challenge
    const command = new RespondToAuthChallengeCommand({
      ChallengeName: "SOFTWARE_TOKEN_MFA", // For TOTP (software-based MFA)
      ClientId: clientID, // Add your Cognito Client ID here
      Session: session, // Use session returned from login step
      ChallengeResponses: {
        USERNAME: email, // Email or username
        SOFTWARE_TOKEN_MFA_CODE: mfaCode, // MFA code entered by the user
      },
    });

    const response = await client.send(command);

    //console.log("MFA authentication response: ", response);

    // If authentication is successful, return tokens (idToken, accessToken, refreshToken)
    if (response.AuthenticationResult) {
      // Check if the user is part of the Admin group
      const poolId = await getUserPoolId();

      const listGroupsCommand = new AdminListGroupsForUserCommand({
        UserPoolId: poolId,
        Username: email,
      });

      const groupResponse = await client.send(listGroupsCommand);

      // Check if the user belongs to the Admin group
      const isAdmin = groupResponse.Groups.some((group) => group.GroupName === "admin") ? true : false;

      res.status(200).json({
        idToken: response.AuthenticationResult.IdToken,
        accessToken: response.AuthenticationResult.AccessToken,
        refreshToken: response.AuthenticationResult.RefreshToken,
        token_type: response.AuthenticationResult.TokenType,
        expires_in: response.AuthenticationResult.ExpiresIn,
        isAdmin: isAdmin, // True if user is in Admin group, false otherwise
      });
    } else {
      res.status(400).json({ message: "Failed to authenticate MFA" });
    }
  } catch (err) {
    console.error("Error during MFA authentication:", err);
    res.status(500).json({ message: "Error during MFA authentication", error: err });
  }
});

module.exports = router;
